export const movieAction = {
  FETCH_DATA_SAGA: "FETCH_DATA_SAGA",
  FETCH_INFORMATION_MOVIE_SAGA: "FETCH_INFORMATION_MOVIE_SAGA",
  FETCH_DETAIL_MOVIE_SAGA: "FETCH_DETAIL_MOVIE_SAGA",
  FETCH_INFORMATION_SHOW_TIMES: "FETCH_INFORMATION_SHOW_TIMES",
  FETCH_INFORMATION_SEAT: "FETCH_INFORMATION_SEAT",
};
